language: node_js
node_js:
  - 14
install: npm i
script: CI=false npm run build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $S3_BUCKET
  local_dir: build
  skip_cleanup: true
